version: "3.9"

services:
  database:
    image: mariadb:10.11
    restart: unless-stopped
    command:
      - mariadbd
      - --innodb-use-native-aio=0
      - --innodb-flush-log-at-trx-commit=2
    environment:
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASS}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_ROOT_PASSWORD: "${DB_PASS}"
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - "./database/dumps/:/docker-entrypoint-initdb.d:ro"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    depends_on:
      - database

volumes:
  db_data: