from .Text import (
    getMainMenu,
    getTrainingOptionalMenu,
    getDifficultyMenu,
    getTrainingTestMenu,
    getIntensiveTestMenu,
    getMarathonTestMenu,
    get_ads_text,
    get_streak_extinguished_text,
    get_streak_warning_text,
)
from .Menu import (
    main_menu_keybord,
    choose_train_menu,
    era_diff_keyboard,
    notification_and_back_keyboard,
    get_choose_train,
    culture_choose_menu,
    get_main_menu_keyboard,
)
__all__ = [
    "getMainMenu",
    "getTrainingOptionalMenu",
    "getTrainingTestMenu",
    "getIntensiveTestMenu",
    "getMarathonTestMenu",
    "get_ads_text",
    "get_streak_extinguished_text",
    "get_streak_warning_text",
    "main_menu_keybord",
    "choose_train_menu",
    "era_diff_keyboard",
    "notification_and_back_keyboard",
    "get_choose_train",
    "culture_choose_menu",
    "get_main_menu_keyboard",
]
